site_name: Embedding-Kit
nav:
  - Home: index.md
  - About: about.md
  - Release Notes: change-notes.md
  - Core Concepts: concepts.md
  - Training Guide: training.md
  - CLI Reference: cli.md
  - Examples:
      - GTEx RNA-seq: examples/gtex.md
      - Protein Encoding: examples/protein.md
      - NetVAE (Pathway): examples/netvae.md
  - API:
      - Overview: api/index.md
      - Helpers & Data Adapters: api/helpers.md
      - Factory:
          - Overview: api/factory/index.md
          - Decorators Example: examples/factory.md
      - Models:
          - Overview: api/models/index.md
          - VAE: api/models/vae.md
          - RNAVAE: api/models/rna_vae.md
          - NetVAE: api/models/net_vae.md
          - FFNN: api/models/ffnn.md
          - PairPredictor: api/models/pair.md
      - Training:
          - Optimize: api/optimize.md
      - Preprocessing: api/preprocessing.md
      - Modules:
          - Overview: api/layers/layers.md
          - Layer & LayerList: api/layers/layer_info.md
          - Masked Linear: api/layers/masked_linear.md
          - Pairwise Comparison: api/layers/pairwise_comparison_layer.md
          - Top Scoring Pair: api/layers/tsp.md
      - Losses:
          - Overview: api/losses/index.md
          - VAE Loss: api/losses/vae_loss.md
      - Constraints:
          - Overview: api/constraints/index.md
      - Metrics:
          - Distance: api/metrics/distance.md
      - Estimator:
          - Overview: api/estimator/index.md
          - VAE Estimator: api/estimator/vae_estimator.md
      - Commands:
          - Overview: api/commands/index.md
          - cbio: api/commands/cbio.md
      - Resources: api/resources/index.md
      - Files: api/files/index.md
      - Encoding: api/encoding/index.md
      - Utilities: api/utilities/index.md
      - Align: api/align.md
      - BMEG: api/bmeg.md
      - Pathway: api/pathway.md

theme: readthedocs

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false

markdown_extensions:
    - mkdocs-click
