name: PR Coverage Check

on: [ pull_request ]

permissions:
  contents: read
  pull-requests: write

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV

    - name: Install library
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -e .

    - name: Run unittests with coverage
      run: |
        export PYTHONPATH=$PWD/src
        python -m coverage erase
        python -m coverage run --source=embkit -m unittest discover -s tests
        COVERAGE_OMIT='src/embkit/bmeg.py,src/embkit/estimator/*,src/embkit/metrics/*,src/embkit/models/ffnn.py,src/embkit/encoding/genome.py,src/embkit/preprocessing/dataset.py,src/embkit/resources/util.py,src/embkit/utilities/kmeans.py'
        python -m coverage xml --omit="$COVERAGE_OMIT"

    - name: Print coverage report
      run: |
        COVERAGE_OMIT='src/embkit/bmeg.py,src/embkit/estimator/*,src/embkit/metrics/*,src/embkit/models/ffnn.py,src/embkit/encoding/genome.py,src/embkit/preprocessing/dataset.py,src/embkit/resources/util.py,src/embkit/utilities/kmeans.py'
        python -m coverage report -m --omit="$COVERAGE_OMIT"

    - name: Comment PR with coverage
      if: github.event.pull_request.head.repo.full_name == github.repository
      uses: orgoro/coverage@v3.2
      with:
        coverageFile: coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        thresholdNew: 0.6
        thresholdAll: 0.3
        thresholdModified: 0.8
